kind: Service
apiVersion: v1
metadata:
  name:  techtrends
  namespace: sandbox
spec:
  selector:
    app:  techtrends
  type:  {{ .Values.service.type }}
  ports:
  - name:  http
    protocol: {{ .Values.service.protocol }}
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.targetPort }}